remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Documentaci贸n

nombres: Juan Miguel G贸mez Carmona
submodulo: L贸gica de Programaci贸n
periodo: 2023-2
url_foto: https://firebasestorage.googleapis.com/v0/b/proyecto-integrador-35564.appspot.com/o/Juan%20Miguel%20G%C3%B3mez.png?alt=media&token=a189072b-dece-49e5-a2b7-03d5869f98f7

